services:
  - type: web
    name: truthtrack-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: "6701a4274emsh7a0d625386d78f2p1c5863jsn78f437bc6c76"
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    autoDeploy: true